### ISSUE TITLE
바탕화면 슬라이드쇼 사용시 SHELLDLL_DefView를 가져올수없습니다

### ISSUE THREAD

**Issue by gmlwns2000** [iodes/DeskShell#1]
바탕화면 슬라이드쇼 사용시 ProgMan을 통해 쉘 윈도우 핸들을 가져오지 못한다 합니다

http://stackoverflow.com/questions/36566675/winapi-how-to-obtain-shelldll-defview

**Comment by iodes** [comment]
Progman 없이 SHELLDLL_DefView 핸들을
바로 검색할 수 있도록 쉘 유틸리티를 수정하였습니다.

28389340bdb6dbcdb71988646e42b9c17edb1fb9
